version: 2

jobs:
  build-job:
    working_directory: ~/demo
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk
    steps: 
      - checkout # Checkout the code from Github
      - run: mvn clean install
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-0.0.1-SNAPSHOT.jar
      - run:
          name: build and push Docker image
          command: |
            TAG=2.1.$CIRCLE_BUILD_NUM
            docker build -t winnie2949/demo:$TAG .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
            docker push winnie2949/demo:$TAG
  deploy-job:
    docker:
      - image: winnie2949/demo:2.1.$CIRCLE_BUILD_NUM
        auth:
          username: linw2949@gmail.com
          password: 4xS?Cwm,xiKa(Q.
    working_directory: /tmp/my-project
    steps:
      - run:
          name: Deploy Main to GKE
          command: |
            sudo /opt/google-cloud-sdk/bin/gcloud docker push us.gcr.io/demo/hello
            sudo chown -R ubuntu:ubuntu /home/ubuntu/.kube
            kubectl patch deployment docker-hello-google -p '{"spec":{"template":{"spec":{"containers":[{"name":"docker-hello-google","image":"us.gcr.io/circle-ctl-test/hello:'"$CIRCLE_SHA1"'"}]}}}}'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job # Only deploy once the build job has completed
          filters:
            branches:
              only: main # Only deploy on the main branch